# Generated by Django 3.2.7 on 2023-04-28 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airpods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('version', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
                ('year', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('version', models.CharField(max_length=127)),
                ('gb', models.CharField(max_length=127)),
                ('color', models.CharField(max_length=127)),
                ('year', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Macbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=127)),
                ('version', models.CharField(max_length=127)),
                ('gb', models.CharField(max_length=127)),
                ('year', models.CharField(max_length=127)),
            ],
        ),
    ]
